/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Luis
 */
public class AddEditBook extends javax.swing.JFrame {

    /**
     * Creates new form AddEditBook
     */
    public AddEditBook() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE); // Cierra solo la ventana en la que activa.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddEditPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        txtTitle = new javax.swing.JTextField();
        txtAuthor = new javax.swing.JTextField();
        txtEditorial = new javax.swing.JTextField();
        txtEdition = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCategory = new javax.swing.JTextField();
        txtLenguge = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtBFree = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtShelf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtSection = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtDepartment = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        txtYearPublication = new com.toedter.calendar.JYearChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(700, 450));
        setMinimumSize(new java.awt.Dimension(700, 450));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddEditPanel.setBackground(new java.awt.Color(255, 255, 255));
        AddEditPanel.setMaximumSize(new java.awt.Dimension(700, 450));
        AddEditPanel.setMinimumSize(new java.awt.Dimension(700, 450));
        AddEditPanel.setPreferredSize(new java.awt.Dimension(700, 450));
        AddEditPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblTitle.setText("Agregar/Editar libro");
        AddEditPanel.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setText("ISBN:");
        AddEditPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel3.setText("Titulo:");
        AddEditPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel4.setText("Autor:");
        AddEditPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel5.setText("Editorial:");
        AddEditPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel6.setText("Edicion:");
        AddEditPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel7.setText("Año de Publicacion:");
        AddEditPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));
        AddEditPanel.add(txtISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 260, -1));
        AddEditPanel.add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 260, -1));
        AddEditPanel.add(txtAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 260, -1));
        AddEditPanel.add(txtEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 260, -1));
        AddEditPanel.add(txtEdition, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 100, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        AddEditPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 10, 340));

        jLabel8.setText("Idioma:");
        AddEditPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        jLabel9.setText("Categoria:");
        AddEditPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        jLabel10.setText("Stock");
        AddEditPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        jLabel11.setText("Disponibles");
        AddEditPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, -1));
        AddEditPanel.add(txtCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 290, -1));
        AddEditPanel.add(txtLenguge, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 290, -1));
        AddEditPanel.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 120, -1));
        AddEditPanel.add(txtBFree, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 140, -1));

        btnSave.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diskette.png"))); // NOI18N
        btnSave.setText("Guardar");
        btnSave.setBorderPainted(false);
        btnSave.setContentAreaFilled(false);
        btnSave.setDefaultCapable(false);
        btnSave.setIconTextGap(12);
        AddEditPanel.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 140, -1));

        jLabel12.setText("Estante:");
        AddEditPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));
        AddEditPanel.add(txtShelf, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 80, -1));

        jLabel13.setText("Sección:");
        AddEditPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));
        AddEditPanel.add(txtSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 90, -1));

        jLabel14.setText("Departamento:");
        AddEditPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));
        AddEditPanel.add(txtDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 110, -1));

        btnCancel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/multiply.png"))); // NOI18N
        btnCancel.setText("Cancelar");
        btnCancel.setBorderPainted(false);
        btnCancel.setContentAreaFilled(false);
        btnCancel.setFocusable(false);
        btnCancel.setIconTextGap(12);
        AddEditPanel.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));
        AddEditPanel.add(txtYearPublication, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 120, -1));

        getContentPane().add(AddEditPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEditBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEditBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEditBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEditBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEditBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel AddEditPanel;
    public javax.swing.JButton btnCancel;
    public javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lblTitle;
    public javax.swing.JTextField txtAuthor;
    public javax.swing.JTextField txtBFree;
    public javax.swing.JTextField txtCategory;
    public javax.swing.JTextField txtDepartment;
    public javax.swing.JTextField txtEdition;
    public javax.swing.JTextField txtEditorial;
    public javax.swing.JTextField txtISBN;
    public javax.swing.JTextField txtLenguge;
    public javax.swing.JTextField txtSection;
    public javax.swing.JTextField txtShelf;
    public javax.swing.JTextField txtStock;
    public javax.swing.JTextField txtTitle;
    public com.toedter.calendar.JYearChooser txtYearPublication;
    // End of variables declaration//GEN-END:variables

 
}   
