/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Luis
 */
public class AddEditUser extends javax.swing.JFrame {

    /**
     * Creates new form AddEditUser
     */
    public AddEditUser() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE); // Cierra solo la ventana en la que activa.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddEditPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblControlNumber = new javax.swing.JLabel();
        lblNames = new javax.swing.JLabel();
        lblLastName1 = new javax.swing.JLabel();
        lblCollegeCareer = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        txtControlNumber = new javax.swing.JTextField();
        txtNames = new javax.swing.JTextField();
        btnCollegeCareer = new javax.swing.JComboBox<>();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtLastNames = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnBanned = new javax.swing.JCheckBox();
        section = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 450));
        setMinimumSize(new java.awt.Dimension(700, 450));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddEditPanel.setBackground(new java.awt.Color(255, 255, 255));
        AddEditPanel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        AddEditPanel.setMaximumSize(new java.awt.Dimension(700, 450));
        AddEditPanel.setMinimumSize(new java.awt.Dimension(700, 450));
        AddEditPanel.setPreferredSize(new java.awt.Dimension(700, 450));
        AddEditPanel.setRequestFocusEnabled(false);
        AddEditPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lblTitle.setText("Registrar/Editar informacion usuario");
        AddEditPanel.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        lblControlNumber.setText("No. Control");
        AddEditPanel.add(lblControlNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        lblNames.setText("Nombre(s):");
        AddEditPanel.add(lblNames, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        lblLastName1.setText("Apellidos:");
        AddEditPanel.add(lblLastName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        lblCollegeCareer.setText("Carrera:");
        AddEditPanel.add(lblCollegeCareer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        lblPhone.setText("Telefono:");
        AddEditPanel.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        lblEmail.setText("Correo:");
        AddEditPanel.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        lblAddress.setText("Domicilio:");
        AddEditPanel.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));
        AddEditPanel.add(txtControlNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 240, -1));
        AddEditPanel.add(txtNames, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 240, -1));

        btnCollegeCareer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        AddEditPanel.add(btnCollegeCareer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 240, -1));
        AddEditPanel.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 240, -1));
        AddEditPanel.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 280, -1));

        btnSave.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diskette.png"))); // NOI18N
        btnSave.setText("Guardar");
        btnSave.setContentAreaFilled(false);
        btnSave.setFocusPainted(false);
        btnSave.setFocusable(false);
        btnSave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSave.setIconTextGap(12);
        btnSave.setMargin(new java.awt.Insets(2, 10, 2, 10));
        AddEditPanel.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 130, -1));
        AddEditPanel.add(txtLastNames, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 240, -1));

        btnCancel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/multiply.png"))); // NOI18N
        btnCancel.setText("Cancelar");
        btnCancel.setContentAreaFilled(false);
        btnCancel.setFocusPainted(false);
        btnCancel.setFocusable(false);
        btnCancel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCancel.setIconTextGap(12);
        btnCancel.setMargin(new java.awt.Insets(2, 10, 2, 10));
        AddEditPanel.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 130, -1));

        btnBanned.setText("Baneado");
        AddEditPanel.add(btnBanned, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 280, -1));

        section.setOrientation(javax.swing.SwingConstants.VERTICAL);
        AddEditPanel.add(section, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, 290));

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        AddEditPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 280, 120));

        getContentPane().add(AddEditPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEditUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel AddEditPanel;
    public javax.swing.JCheckBox btnBanned;
    public javax.swing.JButton btnCancel;
    public javax.swing.JComboBox<String> btnCollegeCareer;
    public javax.swing.JButton btnSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCollegeCareer;
    private javax.swing.JLabel lblControlNumber;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLastName1;
    private javax.swing.JLabel lblNames;
    private javax.swing.JLabel lblPhone;
    public javax.swing.JLabel lblTitle;
    private javax.swing.JSeparator section;
    public javax.swing.JTextArea txtAddress;
    public javax.swing.JTextField txtControlNumber;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtLastNames;
    public javax.swing.JTextField txtNames;
    public javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
