/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ResourceBundle;
import static javax.swing.AbstractButton.FOCUS_PAINTED_CHANGED_PROPERTY;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author Luis
 */
public class Dashboard extends javax.swing.JFrame {
    
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPanel = new JPanel();
        SidebarPanel = new JPanel();
        LogoTec = new JLabel();
        HomeNav = new JPanel();
        btnHome = new JButton();
        LoanNav = new JPanel();
        btnLoan = new JButton();
        ReturnNav = new JPanel();
        btnReturn = new JButton();
        UserNav = new JPanel();
        btnUser = new JButton();
        BookNav = new JPanel();
        btnBook = new JButton();
        ReportNav = new JPanel();
        btnReport = new JButton();
        SettingNav = new JPanel();
        btnSetting = new JButton();
        ContentPanel = new JPanel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new Dimension(1280, 750));
        setName("Form"); // NOI18N
        setResizable(false);

        BackgroundPanel.setBackground(new Color(255, 255, 255));
        BackgroundPanel.setMaximumSize(new Dimension(1280, 750));
        BackgroundPanel.setMinimumSize(new Dimension(1280, 750));
        BackgroundPanel.setName("BackgroundPanel"); // NOI18N
        BackgroundPanel.setLayout(new AbsoluteLayout());

        SidebarPanel.setBackground(new Color(32, 104, 108));
        SidebarPanel.setAutoscrolls(true);
        SidebarPanel.setMaximumSize(new Dimension(280, 750));
        SidebarPanel.setMinimumSize(new Dimension(280, 750));
        SidebarPanel.setName("SidebarPanel"); // NOI18N
        SidebarPanel.setLayout(new AbsoluteLayout());

        LogoTec.setIcon(new ImageIcon(getClass().getResource("/images/logoTecnm.png"))); // NOI18N
        LogoTec.setName("LogoTec"); // NOI18N
        SidebarPanel.add(LogoTec, new AbsoluteConstraints(10, 10, -1, -1));

        HomeNav.setBackground(new Color(32, 104, 108));
        HomeNav.setCursor(new Cursor(Cursor.HAND_CURSOR));
        HomeNav.setFont(new Font("Roboto", 0, 18)); // NOI18N
        HomeNav.setMaximumSize(new Dimension(280, 50));
        HomeNav.setMinimumSize(new Dimension(280, 50));
        HomeNav.setName("HomeNav"); // NOI18N
        HomeNav.setPreferredSize(new Dimension(280, 50));
        HomeNav.setLayout(new GridLayout(1, 0));

        btnHome.setFont(new Font("Roboto", 0, 18)); // NOI18N
        btnHome.setIcon(new ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        ResourceBundle bundle = ResourceBundle.getBundle("System/Dashboard"); // NOI18N
        btnHome.setText(bundle.getString("btnHome")); // NOI18N
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.setFocusPainted(false);
        btnHome.setHorizontalAlignment(SwingConstants.LEFT);
        btnHome.setIconTextGap(24);
        btnHome.setMargin(new Insets(2, 25, 2, 25));
        btnHome.setName("btnHome"); // NOI18N
        HomeNav.add(btnHome);

        SidebarPanel.add(HomeNav, new AbsoluteConstraints(0, 160, 280, 50));

        LoanNav.setBackground(new Color(32, 104, 108));
        LoanNav.setCursor(new Cursor(Cursor.HAND_CURSOR));
        LoanNav.setMaximumSize(new Dimension(280, 50));
        LoanNav.setMinimumSize(new Dimension(280, 50));
        LoanNav.setName("LoanNav"); // NOI18N
        LoanNav.setPreferredSize(new Dimension(280, 50));
        LoanNav.setLayout(new GridLayout(1, 0));

        btnLoan.setFont(new Font("Roboto", 0, 18)); // NOI18N
        btnLoan.setIcon(new ImageIcon(getClass().getResource("/images/deal.png"))); // NOI18N
        btnLoan.setText(bundle.getString("btnLoan")); // NOI18N
        btnLoan.setBorderPainted(false);
        btnLoan.setContentAreaFilled(false);
        btnLoan.setFocusPainted(false);
        btnLoan.setHideActionText(true);
        btnLoan.setHorizontalAlignment(SwingConstants.LEFT);
        btnLoan.setIconTextGap(24);
        btnLoan.setMargin(new Insets(2, 25, 2, 25));
        btnLoan.setName("btnLoan"); // NOI18N
        LoanNav.add(btnLoan);

        SidebarPanel.add(LoanNav, new AbsoluteConstraints(0, 210, -1, -1));

        ReturnNav.setBackground(new Color(32, 104, 108));
        ReturnNav.setCursor(new Cursor(Cursor.HAND_CURSOR));
        ReturnNav.setMaximumSize(new Dimension(280, 50));
        ReturnNav.setMinimumSize(new Dimension(280, 50));
        ReturnNav.setName("ReturnNav"); // NOI18N
        ReturnNav.setPreferredSize(new Dimension(280, 50));
        ReturnNav.setLayout(new GridLayout(1, 0));

        btnReturn.setFont(new Font("Roboto", 0, 18)); // NOI18N
        btnReturn.setIcon(new ImageIcon(getClass().getResource("/images/return.png"))); // NOI18N
        btnReturn.setText(bundle.getString("btnReturn")); // NOI18N
        btnReturn.setBorderPainted(false);
        btnReturn.setContentAreaFilled(false);
        btnReturn.setFocusPainted(false);
        btnReturn.setHorizontalAlignment(SwingConstants.LEFT);
        btnReturn.setIconTextGap(24);
        btnReturn.setMargin(new Insets(2, 25, 2, 25));
        btnReturn.setName("btnReturn"); // NOI18N
        ReturnNav.add(btnReturn);

        SidebarPanel.add(ReturnNav, new AbsoluteConstraints(0, 260, -1, -1));

        UserNav.setBackground(new Color(32, 104, 108));
        UserNav.setCursor(new Cursor(Cursor.HAND_CURSOR));
        UserNav.setMaximumSize(new Dimension(280, 50));
        UserNav.setMinimumSize(new Dimension(280, 50));
        UserNav.setName("UserNav"); // NOI18N
        UserNav.setPreferredSize(new Dimension(280, 50));
        UserNav.setLayout(new GridLayout(1, 0));

        btnUser.setFont(new Font("Roboto", 0, 18)); // NOI18N
        btnUser.setIcon(new ImageIcon(getClass().getResource("/images/man.png"))); // NOI18N
        btnUser.setText(bundle.getString("btnUser")); // NOI18N
        btnUser.setBorderPainted(false);
        btnUser.setContentAreaFilled(false);
        btnUser.setFocusPainted(false);
        btnUser.setHorizontalAlignment(SwingConstants.LEFT);
        btnUser.setIconTextGap(24);
        btnUser.setMargin(new Insets(2, 25, 2, 25));
        btnUser.setName("btnUser"); // NOI18N
        UserNav.add(btnUser);

        SidebarPanel.add(UserNav, new AbsoluteConstraints(0, 310, -1, -1));

        BookNav.setBackground(new Color(32, 104, 108));
        BookNav.setCursor(new Cursor(Cursor.HAND_CURSOR));
        BookNav.setMaximumSize(new Dimension(280, 50));
        BookNav.setMinimumSize(new Dimension(280, 50));
        BookNav.setName("BookNav"); // NOI18N
        BookNav.setPreferredSize(new Dimension(280, 50));
        BookNav.setLayout(new GridLayout(1, 0));

        btnBook.setFont(new Font("Roboto", 0, 18)); // NOI18N
        btnBook.setIcon(new ImageIcon(getClass().getResource("/images/books.png"))); // NOI18N
        btnBook.setText(bundle.getString("btnBook")); // NOI18N
        btnBook.setBorderPainted(false);
        btnBook.setContentAreaFilled(false);
        btnBook.setFocusPainted(false);
        btnBook.setHorizontalAlignment(SwingConstants.LEFT);
        btnBook.setIconTextGap(24);
        btnBook.setMargin(new Insets(2, 25, 2, 25));
        btnBook.setName("btnBook"); // NOI18N
        BookNav.add(btnBook);

        SidebarPanel.add(BookNav, new AbsoluteConstraints(0, 360, -1, -1));

        ReportNav.setBackground(new Color(32, 104, 108));
        ReportNav.setCursor(new Cursor(Cursor.HAND_CURSOR));
        ReportNav.setMaximumSize(new Dimension(280, 50));
        ReportNav.setMinimumSize(new Dimension(280, 50));
        ReportNav.setName(""); // NOI18N
        ReportNav.setPreferredSize(new Dimension(280, 50));
        ReportNav.setLayout(new GridLayout(1, 0));

        btnReport.setFont(new Font("Roboto", 0, 18)); // NOI18N
        btnReport.setIcon(new ImageIcon(getClass().getResource("/images/clipboard.png"))); // NOI18N
        btnReport.setText(bundle.getString("btnReport")); // NOI18N
        btnReport.setBorderPainted(false);
        btnReport.setContentAreaFilled(false);
        btnReport.setDefaultCapable(false);
        btnReport.setFocusPainted(false);
        btnReport.setHorizontalAlignment(SwingConstants.LEFT);
        btnReport.setIconTextGap(24);
        btnReport.setMargin(new Insets(2, 25, 2, 25));
        btnReport.setName("btnReport"); // NOI18N
        ReportNav.add(btnReport);

        SidebarPanel.add(ReportNav, new AbsoluteConstraints(0, 410, -1, -1));

        SettingNav.setBackground(new Color(32, 104, 108));
        SettingNav.setCursor(new Cursor(Cursor.HAND_CURSOR));
        SettingNav.setMaximumSize(new Dimension(280, 50));
        SettingNav.setMinimumSize(new Dimension(280, 50));
        SettingNav.setName("SettingNav"); // NOI18N
        SettingNav.setPreferredSize(new Dimension(280, 50));
        SettingNav.setLayout(new GridLayout(1, 0));

        btnSetting.setFont(new Font("Roboto", 0, 18)); // NOI18N
        btnSetting.setIcon(new ImageIcon(getClass().getResource("/images/setting.png"))); // NOI18N
        btnSetting.setText(bundle.getString("btnSetting")); // NOI18N
        btnSetting.setBorderPainted(false);
        btnSetting.setContentAreaFilled(false);
        btnSetting.setFocusPainted(false);
        btnSetting.setHorizontalAlignment(SwingConstants.LEFT);
        btnSetting.setIconTextGap(24);
        btnSetting.setMargin(new Insets(2, 25, 2, 25));
        btnSetting.setName("btnSetting"); // NOI18N
        SettingNav.add(btnSetting);

        SidebarPanel.add(SettingNav, new AbsoluteConstraints(0, 700, -1, -1));

        BackgroundPanel.add(SidebarPanel, new AbsoluteConstraints(0, 0, 280, 750));

        ContentPanel.setBackground(new Color(255, 255, 255));
        ContentPanel.setMaximumSize(new Dimension(1000, 750));
        ContentPanel.setMinimumSize(new Dimension(1000, 750));
        ContentPanel.setName("ContentPanel"); // NOI18N
        ContentPanel.setPreferredSize(new Dimension(1000, 750));

        GroupLayout ContentPanelLayout = new GroupLayout(ContentPanel);
        ContentPanel.setLayout(ContentPanelLayout);
        ContentPanelLayout.setHorizontalGroup(ContentPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        ContentPanelLayout.setVerticalGroup(ContentPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        BackgroundPanel.add(ContentPanel, new AbsoluteConstraints(280, 0, 1000, 750));

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
         /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Dashboard().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public JPanel BackgroundPanel;
    public JPanel BookNav;
    public JPanel ContentPanel;
    public JPanel HomeNav;
    public JPanel LoanNav;
    public JLabel LogoTec;
    public JPanel ReportNav;
    public JPanel ReturnNav;
    public JPanel SettingNav;
    public JPanel SidebarPanel;
    public JPanel UserNav;
    public JButton btnBook;
    public JButton btnHome;
    public JButton btnLoan;
    public JButton btnReport;
    public JButton btnReturn;
    public JButton btnSetting;
    public JButton btnUser;
    // End of variables declaration//GEN-END:variables
}
