/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

/**
 *
 * @author Luis
 */
public class HomeView extends javax.swing.JPanel {

    /** Creates new form HomeView */
    public HomeView() {
        initComponents();
        
        // Componentes que deben estar desabilitados en un inicio.
        this.lblWelcome.setVisible(false);
        this.lblLoggedUser.setVisible(false);
        this.btnLogout.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgHome = new javax.swing.JPanel();
        SignUpLoginPanel = new javax.swing.JPanel();
        LoginSignUp = new javax.swing.JTabbedPane();
        LoginPanel = new javax.swing.JPanel();
        lblLoginUser = new javax.swing.JLabel();
        txtLoginNickName = new javax.swing.JTextField();
        lblLoginPassword = new javax.swing.JLabel();
        btnRememberMe = new javax.swing.JCheckBox();
        txtLoginPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        Separator = new javax.swing.JSeparator();
        SignUpPanel = new javax.swing.JPanel();
        lblSignUpNames = new javax.swing.JLabel();
        txtSignUpNames = new javax.swing.JTextField();
        lblSignUpLastNames = new javax.swing.JLabel();
        txtSignUpLastNames = new javax.swing.JTextField();
        lblSignUpEmail = new javax.swing.JLabel();
        txtSignUpEmail = new javax.swing.JTextField();
        lblSignUpPassword = new javax.swing.JLabel();
        txtSignUpPassword = new javax.swing.JPasswordField();
        lblSignUpRepass = new javax.swing.JLabel();
        txtSignUpRepass = new javax.swing.JPasswordField();
        lblSignUpNickName = new javax.swing.JLabel();
        txtSignUpNickName = new javax.swing.JTextField();
        btnSignUp = new javax.swing.JButton();
        lblLoggedUser = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        MessagePanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 750));
        setMinimumSize(new java.awt.Dimension(1000, 750));
        setPreferredSize(new java.awt.Dimension(1000, 750));

        bgHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignUpLoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        SignUpLoginPanel.setMaximumSize(new java.awt.Dimension(400, 750));
        SignUpLoginPanel.setMinimumSize(new java.awt.Dimension(400, 750));
        SignUpLoginPanel.setPreferredSize(new java.awt.Dimension(400, 750));
        SignUpLoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginSignUp.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        LoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        LoginPanel.setMaximumSize(new java.awt.Dimension(280, 500));
        LoginPanel.setMinimumSize(new java.awt.Dimension(280, 500));
        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLoginUser.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblLoginUser.setText("Usuario:");
        LoginPanel.add(lblLoginUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txtLoginNickName.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtLoginNickName.setMaximumSize(new java.awt.Dimension(6, 30));
        txtLoginNickName.setMinimumSize(new java.awt.Dimension(6, 30));
        txtLoginNickName.setPreferredSize(new java.awt.Dimension(6, 30));
        LoginPanel.add(txtLoginNickName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 321, -1));

        lblLoginPassword.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblLoginPassword.setText("Contraseña:");
        LoginPanel.add(lblLoginPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        btnRememberMe.setBackground(new java.awt.Color(255, 255, 255));
        btnRememberMe.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnRememberMe.setText("Recordar inicio de sesión");
        btnRememberMe.setFocusPainted(false);
        btnRememberMe.setIconTextGap(12);
        LoginPanel.add(btnRememberMe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 321, -1));

        txtLoginPassword.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtLoginPassword.setMaximumSize(new java.awt.Dimension(6, 30));
        txtLoginPassword.setMinimumSize(new java.awt.Dimension(6, 30));
        txtLoginPassword.setPreferredSize(new java.awt.Dimension(6, 30));
        LoginPanel.add(txtLoginPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 320, -1));

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/enter_24.png"))); // NOI18N
        btnLogin.setText("Iniciar Sesión");
        btnLogin.setBorderPainted(false);
        btnLogin.setContentAreaFilled(false);
        btnLogin.setDefaultCapable(false);
        btnLogin.setFocusPainted(false);
        btnLogin.setIconTextGap(12);
        btnLogin.setMargin(new java.awt.Insets(2, 2, 2, 2));
        LoginPanel.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 170, -1));

        Separator.setMaximumSize(new java.awt.Dimension(50, 100));
        Separator.setMinimumSize(new java.awt.Dimension(50, 100));
        Separator.setPreferredSize(new java.awt.Dimension(50, 100));
        LoginPanel.add(Separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 320, 10));

        LoginSignUp.addTab("Ingresar", LoginPanel);

        SignUpPanel.setBackground(new java.awt.Color(255, 255, 255));
        SignUpPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSignUpNames.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblSignUpNames.setText("Nombre(s):");
        SignUpPanel.add(lblSignUpNames, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txtSignUpNames.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtSignUpNames.setMaximumSize(new java.awt.Dimension(7, 30));
        txtSignUpNames.setMinimumSize(new java.awt.Dimension(7, 30));
        txtSignUpNames.setPreferredSize(new java.awt.Dimension(7, 30));
        SignUpPanel.add(txtSignUpNames, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 320, -1));

        lblSignUpLastNames.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblSignUpLastNames.setText("Apellidos:");
        SignUpPanel.add(lblSignUpLastNames, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtSignUpLastNames.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtSignUpLastNames.setMaximumSize(new java.awt.Dimension(6, 30));
        txtSignUpLastNames.setMinimumSize(new java.awt.Dimension(6, 30));
        txtSignUpLastNames.setPreferredSize(new java.awt.Dimension(6, 30));
        SignUpPanel.add(txtSignUpLastNames, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 320, -1));

        lblSignUpEmail.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblSignUpEmail.setText("Correo electronico:");
        SignUpPanel.add(lblSignUpEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        txtSignUpEmail.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtSignUpEmail.setMaximumSize(new java.awt.Dimension(6, 30));
        txtSignUpEmail.setMinimumSize(new java.awt.Dimension(6, 30));
        txtSignUpEmail.setPreferredSize(new java.awt.Dimension(6, 30));
        SignUpPanel.add(txtSignUpEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 320, -1));

        lblSignUpPassword.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblSignUpPassword.setText("Contraseña (>= 6 caracteres):");
        SignUpPanel.add(lblSignUpPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        txtSignUpPassword.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtSignUpPassword.setMaximumSize(new java.awt.Dimension(6, 30));
        txtSignUpPassword.setMinimumSize(new java.awt.Dimension(6, 30));
        txtSignUpPassword.setPreferredSize(new java.awt.Dimension(6, 30));
        SignUpPanel.add(txtSignUpPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 320, -1));

        lblSignUpRepass.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblSignUpRepass.setText("Confirmar Contraseña:");
        SignUpPanel.add(lblSignUpRepass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        txtSignUpRepass.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtSignUpRepass.setMaximumSize(new java.awt.Dimension(6, 30));
        txtSignUpRepass.setMinimumSize(new java.awt.Dimension(6, 30));
        txtSignUpRepass.setPreferredSize(new java.awt.Dimension(6, 30));
        SignUpPanel.add(txtSignUpRepass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 320, -1));

        lblSignUpNickName.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblSignUpNickName.setText("Nombre de Usuario:");
        SignUpPanel.add(lblSignUpNickName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtSignUpNickName.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtSignUpNickName.setMaximumSize(new java.awt.Dimension(6, 30));
        txtSignUpNickName.setMinimumSize(new java.awt.Dimension(6, 30));
        txtSignUpNickName.setPreferredSize(new java.awt.Dimension(6, 30));
        SignUpPanel.add(txtSignUpNickName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 320, -1));

        btnSignUp.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/patient.png"))); // NOI18N
        btnSignUp.setText("Registrar");
        btnSignUp.setBorderPainted(false);
        btnSignUp.setContentAreaFilled(false);
        btnSignUp.setDefaultCapable(false);
        btnSignUp.setIconTextGap(12);
        SignUpPanel.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 160, -1));

        LoginSignUp.addTab("Registrar", SignUpPanel);

        SignUpLoginPanel.add(LoginSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 370, 470));
        LoginSignUp.getAccessibleContext().setAccessibleName("");

        lblLoggedUser.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblLoggedUser.setText("Luis Mario Chávez Martínez");
        SignUpLoginPanel.add(lblLoggedUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        lblWelcome.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lblWelcome.setText("Bienvenido:");
        SignUpLoginPanel.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        btnLogout.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        btnLogout.setText("Cerrar Sesión");
        btnLogout.setBorderPainted(false);
        btnLogout.setContentAreaFilled(false);
        btnLogout.setFocusPainted(false);
        btnLogout.setIconTextGap(12);
        btnLogout.setMargin(new java.awt.Insets(2, 2, 2, 2));
        SignUpLoginPanel.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 170, -1));

        bgHome.add(SignUpLoginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));

        MessagePanel.setBackground(new java.awt.Color(204, 255, 255));
        MessagePanel.setMaximumSize(new java.awt.Dimension(600, 750));
        MessagePanel.setMinimumSize(new java.awt.Dimension(600, 750));
        MessagePanel.setName(""); // NOI18N
        MessagePanel.setPreferredSize(new java.awt.Dimension(600, 750));

        javax.swing.GroupLayout MessagePanelLayout = new javax.swing.GroupLayout(MessagePanel);
        MessagePanel.setLayout(MessagePanelLayout);
        MessagePanelLayout.setHorizontalGroup(
            MessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        MessagePanelLayout.setVerticalGroup(
            MessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        bgHome.add(MessagePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(588, 588, 588))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel LoginPanel;
    public javax.swing.JTabbedPane LoginSignUp;
    public javax.swing.JPanel MessagePanel;
    private javax.swing.JSeparator Separator;
    public javax.swing.JPanel SignUpLoginPanel;
    public javax.swing.JPanel SignUpPanel;
    public javax.swing.JPanel bgHome;
    public javax.swing.JButton btnLogin;
    public javax.swing.JButton btnLogout;
    public javax.swing.JCheckBox btnRememberMe;
    public javax.swing.JButton btnSignUp;
    public javax.swing.JLabel lblLoggedUser;
    private javax.swing.JLabel lblLoginPassword;
    private javax.swing.JLabel lblLoginUser;
    private javax.swing.JLabel lblSignUpEmail;
    private javax.swing.JLabel lblSignUpLastNames;
    private javax.swing.JLabel lblSignUpNames;
    public javax.swing.JLabel lblSignUpNickName;
    private javax.swing.JLabel lblSignUpPassword;
    private javax.swing.JLabel lblSignUpRepass;
    public javax.swing.JLabel lblWelcome;
    public javax.swing.JTextField txtLoginNickName;
    public javax.swing.JPasswordField txtLoginPassword;
    public javax.swing.JTextField txtSignUpEmail;
    public javax.swing.JTextField txtSignUpLastNames;
    public javax.swing.JTextField txtSignUpNames;
    public javax.swing.JTextField txtSignUpNickName;
    public javax.swing.JPasswordField txtSignUpPassword;
    public javax.swing.JPasswordField txtSignUpRepass;
    // End of variables declaration//GEN-END:variables

}
