/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.ImageIcon;

/**
 *
 * @author Luis
 */
public class LoanView extends javax.swing.JPanel {

    /**
     * Creates new form LoanView
     */
    public LoanView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgLoan = new javax.swing.JPanel();
        fullLoanInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNLoan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblT = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblBookAuthor = new javax.swing.JLabel();
        lblBookTitle = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblBookEditorial = new javax.swing.JLabel();
        addLoan = new javax.swing.JPanel();
        lblLoanTitle = new javax.swing.JLabel();
        lblControlNumber = new javax.swing.JLabel();
        txtControlNumber = new javax.swing.JTextField();
        lblISBM = new javax.swing.JLabel();
        lblLoanDate = new javax.swing.JLabel();
        lblReturnDate = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblLibrarianLogged = new javax.swing.JLabel();
        lblAutorize = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ReturnDatePicker = new com.toedter.calendar.JDateChooser();
        LoanDatePicker = new com.toedter.calendar.JDateChooser();
        btnClean = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 750));
        setMinimumSize(new java.awt.Dimension(1000, 750));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgLoan.setBackground(new java.awt.Color(0, 0, 0));
        bgLoan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fullLoanInfo.setBackground(new java.awt.Color(255, 255, 255));
        fullLoanInfo.setMaximumSize(new java.awt.Dimension(500, 750));
        fullLoanInfo.setMinimumSize(new java.awt.Dimension(500, 750));
        fullLoanInfo.setPreferredSize(new java.awt.Dimension(500, 750));
        fullLoanInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setText("Información de Préstamo");
        fullLoanInfo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setText("Prestamos Activos: ");
        fullLoanInfo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        txtNLoan.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        fullLoanInfo.add(txtNLoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 40, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel8.setText("/3");
        fullLoanInfo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel9.setText("Nombre Completo:");
        fullLoanInfo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        lblFullName.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        fullLoanInfo.add(lblFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setText("Teléfono:");
        fullLoanInfo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setText("Correo:");
        fullLoanInfo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        lblPhoneNumber.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        fullLoanInfo.add(lblPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        lblEmail.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        fullLoanInfo.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));
        fullLoanInfo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 430, 10));

        lblT.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblT.setText("Título del libro:");
        fullLoanInfo.add(lblT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setText("Nombre del Autor:");
        fullLoanInfo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        lblBookAuthor.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        fullLoanInfo.add(lblBookAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        lblBookTitle.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        fullLoanInfo.add(lblBookTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel6.setText("Editorial:");
        fullLoanInfo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        lblBookEditorial.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        fullLoanInfo.add(lblBookEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, -1, -1));

        bgLoan.add(fullLoanInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, -1, 750));

        addLoan.setBackground(new java.awt.Color(204, 204, 204));
        addLoan.setMaximumSize(new java.awt.Dimension(500, 750));
        addLoan.setMinimumSize(new java.awt.Dimension(500, 750));
        addLoan.setPreferredSize(new java.awt.Dimension(500, 750));
        addLoan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLoanTitle.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lblLoanTitle.setText("Generar un Prestamo");
        addLoan.add(lblLoanTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        lblControlNumber.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblControlNumber.setText("Numero de Control:");
        addLoan.add(lblControlNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        txtControlNumber.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtControlNumber.setMaximumSize(new java.awt.Dimension(6, 30));
        txtControlNumber.setMinimumSize(new java.awt.Dimension(6, 30));
        txtControlNumber.setPreferredSize(new java.awt.Dimension(6, 30));
        addLoan.add(txtControlNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 410, -1));

        lblISBM.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblISBM.setText("Identificador del libro (ISBN):");
        addLoan.add(lblISBM, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        lblLoanDate.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblLoanDate.setText("Fecha Prestamo:");
        addLoan.add(lblLoanDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        lblReturnDate.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblReturnDate.setText("Fecha Devolucion:");
        addLoan.add(lblReturnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        txtISBN.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtISBN.setMaximumSize(new java.awt.Dimension(6, 30));
        txtISBN.setMinimumSize(new java.awt.Dimension(6, 30));
        txtISBN.setPreferredSize(new java.awt.Dimension(6, 30));
        addLoan.add(txtISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 410, -1));

        btnSave.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diskette.png"))); // NOI18N
        btnSave.setText("Guardar");
        btnSave.setBorderPainted(false);
        btnSave.setContentAreaFilled(false);
        btnSave.setFocusable(false);
        btnSave.setIconTextGap(12);
        addLoan.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, -1));

        lblLibrarianLogged.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblLibrarianLogged.setText("Autorizo:");
        addLoan.add(lblLibrarianLogged, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        lblAutorize.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        addLoan.add(lblAutorize, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 360, 20));

        jSeparator1.setPreferredSize(new java.awt.Dimension(100, 10));
        addLoan.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 410, -1));

        ReturnDatePicker.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        ReturnDatePicker.setPreferredSize(new java.awt.Dimension(80, 35));
        addLoan.add(ReturnDatePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 200, -1));

        LoanDatePicker.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        LoanDatePicker.setPreferredSize(new java.awt.Dimension(80, 35));
        addLoan.add(LoanDatePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 180, -1));

        btnClean.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnClean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clean.png"))); // NOI18N
        btnClean.setText("Limpiar");
        btnClean.setBorderPainted(false);
        btnClean.setContentAreaFilled(false);
        btnClean.setFocusable(false);
        btnClean.setIconTextGap(12);
        addLoan.add(btnClean, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));

        bgLoan.add(addLoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 750));

        add(bgLoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 750));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.toedter.calendar.JDateChooser LoanDatePicker;
    public com.toedter.calendar.JDateChooser ReturnDatePicker;
    public javax.swing.JPanel addLoan;
    private javax.swing.JPanel bgLoan;
    public javax.swing.JButton btnClean;
    public javax.swing.JButton btnSave;
    public javax.swing.JPanel fullLoanInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JLabel lblAutorize;
    public javax.swing.JLabel lblBookAuthor;
    public javax.swing.JLabel lblBookEditorial;
    public javax.swing.JLabel lblBookTitle;
    private javax.swing.JLabel lblControlNumber;
    public javax.swing.JLabel lblEmail;
    public javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblISBM;
    private javax.swing.JLabel lblLibrarianLogged;
    private javax.swing.JLabel lblLoanDate;
    private javax.swing.JLabel lblLoanTitle;
    public javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblReturnDate;
    private javax.swing.JLabel lblT;
    public javax.swing.JTextField txtControlNumber;
    public javax.swing.JTextField txtISBN;
    public javax.swing.JTextField txtNLoan;
    // End of variables declaration//GEN-END:variables
}
