/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.ButtonGroup;
/**
 *
 * @author Luis
 */
public class ReportView extends javax.swing.JPanel {

    /**
     * Creates new form ReportView
     */
    public ReportView() {
        initComponents();
        ButtonGroup FilterLoans = new ButtonGroup();
        FilterLoans.add(btnBoth);
        this.btnBoth.setSelected(true);
        FilterLoans.add(btnOnlyDelivered);
        FilterLoans.add(btnOnlySlopes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportsMenu = new javax.swing.JTabbedPane();
        LoansTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LoansTable = new javax.swing.JTable();
        lblTitleTab1 = new javax.swing.JLabel();
        btnExportTab1 = new javax.swing.JButton();
        lblStartDate = new javax.swing.JLabel();
        lblFinishDate = new javax.swing.JLabel();
        FinishDatePicker = new com.toedter.calendar.JDateChooser();
        StartDatePicker = new com.toedter.calendar.JDateChooser();
        btnOnlyDelivered = new javax.swing.JRadioButton();
        btnOnlySlopes = new javax.swing.JRadioButton();
        btnBoth = new javax.swing.JRadioButton();
        BooksTab = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TopBooksTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        MoreActiveCareersTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        MostPenalizedUsersTable = new javax.swing.JTable();
        UsersTab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        BestUsersTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 750));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoansTab.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        LoansTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoansTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "No. Control", "ISBN", "Salida", "Entrega", "Estado", "Renovaciones", "Multa", "Entrego", "Recibio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Long.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(LoansTable);
        if (LoansTable.getColumnModel().getColumnCount() > 0) {
            LoansTable.getColumnModel().getColumn(2).setResizable(false);
            LoansTable.getColumnModel().getColumn(4).setResizable(false);
        }

        LoansTab.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 950, 600));

        lblTitleTab1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lblTitleTab1.setText("Generar un Reporte ");
        LoansTab.add(lblTitleTab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnExportTab1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnExportTab1.setText("Exportar a Excel");
        LoansTab.add(btnExportTab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 680, -1, -1));

        lblStartDate.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblStartDate.setText("Fecha de Inicio:");
        LoansTab.add(lblStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        lblFinishDate.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblFinishDate.setText("Fecha de Finalizacion:");
        LoansTab.add(lblFinishDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        FinishDatePicker.setPreferredSize(new java.awt.Dimension(90, 30));
        LoansTab.add(FinishDatePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 180, -1));

        StartDatePicker.setPreferredSize(new java.awt.Dimension(90, 30));
        LoansTab.add(StartDatePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 180, -1));

        btnOnlyDelivered.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnOnlyDelivered.setText("Solo Entregados");
        LoansTab.add(btnOnlyDelivered, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 680, -1, -1));

        btnOnlySlopes.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnOnlySlopes.setText("Solo Pendientes");
        LoansTab.add(btnOnlySlopes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 680, -1, -1));

        btnBoth.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnBoth.setText("Ambos");
        LoansTab.add(btnBoth, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 680, -1, -1));

        reportsMenu.addTab("Prestamos", LoansTab);

        BooksTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TopBooksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "No. Prestramos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TopBooksTable);

        BooksTab.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 450, 610));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel3.setText("Carreras más Activas");
        BooksTab.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, -1));

        MoreActiveCareersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Carrera", "Total Prestamos "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(MoreActiveCareersTable);

        BooksTab.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 450, 220));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel4.setText("Libros más Solicitados");
        BooksTab.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));
        BooksTab.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 290, 10));
        BooksTab.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));
        BooksTab.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 270, 10));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel2.setText("Usuarios más multados");
        BooksTab.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, -1));
        BooksTab.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 300, 10));

        MostPenalizedUsersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Control", "Prestamos Activos", "Total Multas"
            }
        ));
        jScrollPane4.setViewportView(MostPenalizedUsersTable);

        BooksTab.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, -1, 320));

        reportsMenu.addTab("Top Libros/ Top Carreras", BooksTab);

        UsersTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setText("Ususarios con más prestamos en el periodo");
        UsersTab.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));
        UsersTab.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 560, 10));

        BestUsersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Control", "Carrera", "Nombre Completo", "Total de Prestamos", "Total Multas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(BestUsersTable);

        UsersTab.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 930, 610));

        reportsMenu.addTab("Top Usuarios", UsersTab);

        add(reportsMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 750));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BestUsersTable;
    public javax.swing.JPanel BooksTab;
    public com.toedter.calendar.JDateChooser FinishDatePicker;
    public javax.swing.JPanel LoansTab;
    public javax.swing.JTable LoansTable;
    private javax.swing.JTable MoreActiveCareersTable;
    private javax.swing.JTable MostPenalizedUsersTable;
    public com.toedter.calendar.JDateChooser StartDatePicker;
    private javax.swing.JTable TopBooksTable;
    public javax.swing.JPanel UsersTab;
    public javax.swing.JRadioButton btnBoth;
    public javax.swing.JButton btnExportTab1;
    public javax.swing.JRadioButton btnOnlyDelivered;
    public javax.swing.JRadioButton btnOnlySlopes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblFinishDate;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblTitleTab1;
    public javax.swing.JTabbedPane reportsMenu;
    // End of variables declaration//GEN-END:variables
}
