/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;

/**
 *
 * @author Luis
 */
public class ReportView extends javax.swing.JPanel {

    /**
     * Creates new form ReportView
     */
    public ReportView() {
        initComponents();
        ButtonGroup FilterLoans = new ButtonGroup();
        FilterLoans.add(btnBoth);
        this.btnBoth.setSelected(true);
        FilterLoans.add(btnOnlyDelivered);
        FilterLoans.add(btnOnlySlopes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportsMenu = new javax.swing.JTabbedPane();
        LoansTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LoansTable = new javax.swing.JTable();
        lblTitleTab1 = new javax.swing.JLabel();
        btnExportTab1 = new javax.swing.JButton();
        lblStartDate = new javax.swing.JLabel();
        lblFinishDate = new javax.swing.JLabel();
        FinishDatePicker = new com.toedter.calendar.JDateChooser();
        StartDatePicker = new com.toedter.calendar.JDateChooser();
        btnOnlyDelivered = new javax.swing.JRadioButton();
        btnOnlySlopes = new javax.swing.JRadioButton();
        btnBoth = new javax.swing.JRadioButton();
        BooksTab = new javax.swing.JPanel();
        CareersTab = new javax.swing.JPanel();
        UsersTab = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 750));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoansTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoansTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "No. Control", "ISBN", "Salida", "Entrega", "Estado", "Renovaciones", "Multa", "Entrego", "Recibio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Long.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(LoansTable);
        if (LoansTable.getColumnModel().getColumnCount() > 0) {
            LoansTable.getColumnModel().getColumn(2).setResizable(false);
            LoansTable.getColumnModel().getColumn(4).setResizable(false);
        }

        LoansTab.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 950, 600));

        lblTitleTab1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lblTitleTab1.setText("Generar un Reporte ");
        LoansTab.add(lblTitleTab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnExportTab1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnExportTab1.setText("Exportar a Excel");
        LoansTab.add(btnExportTab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 680, -1, -1));

        lblStartDate.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblStartDate.setText("Fecha de Inicio:");
        LoansTab.add(lblStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        lblFinishDate.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblFinishDate.setText("Fecha de Finalizacion:");
        LoansTab.add(lblFinishDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        FinishDatePicker.setPreferredSize(new java.awt.Dimension(90, 30));
        LoansTab.add(FinishDatePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 180, -1));

        StartDatePicker.setPreferredSize(new java.awt.Dimension(90, 30));
        LoansTab.add(StartDatePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 180, -1));

        btnOnlyDelivered.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnOnlyDelivered.setText("Solo Entregados");
        LoansTab.add(btnOnlyDelivered, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 680, -1, -1));

        btnOnlySlopes.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnOnlySlopes.setText("Solo Pendientes");
        LoansTab.add(btnOnlySlopes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 680, -1, -1));

        btnBoth.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnBoth.setText("Ambos");
        LoansTab.add(btnBoth, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 680, -1, -1));

        reportsMenu.addTab("Prestamos", LoansTab);
        reportsMenu.addTab("Libros Mas Solicitados", BooksTab);
        reportsMenu.addTab("Por Carrera", CareersTab);
        reportsMenu.addTab("Usuarios mas Activos", UsersTab);

        add(reportsMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 750));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel BooksTab;
    public javax.swing.JPanel CareersTab;
    public com.toedter.calendar.JDateChooser FinishDatePicker;
    public javax.swing.JPanel LoansTab;
    public javax.swing.JTable LoansTable;
    public com.toedter.calendar.JDateChooser StartDatePicker;
    public javax.swing.JPanel UsersTab;
    public javax.swing.JRadioButton btnBoth;
    public javax.swing.JButton btnExportTab1;
    public javax.swing.JRadioButton btnOnlyDelivered;
    public javax.swing.JRadioButton btnOnlySlopes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFinishDate;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblTitleTab1;
    public javax.swing.JTabbedPane reportsMenu;
    // End of variables declaration//GEN-END:variables
}
