/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Luis
 */
public class SettingView extends javax.swing.JPanel {

    /**
     * Creates new form SettingView
     */
    public SettingView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GlobalSettings = new javax.swing.JTabbedPane();
        DataBaseSettings = new javax.swing.JPanel();
        ServerSettings = new javax.swing.JPanel();
        lblServerHost = new javax.swing.JLabel();
        lblPort = new javax.swing.JLabel();
        lblDataBase = new javax.swing.JLabel();
        txtServerHost = new javax.swing.JTextField();
        txtServerPort = new javax.swing.JTextField();
        txtDataBaseName = new javax.swing.JTextField();
        AuthenticationSettings = new javax.swing.JPanel();
        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        cboxShowPass = new javax.swing.JCheckBox();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        ActionsSettings = new javax.swing.JPanel();
        btnTestCon = new javax.swing.JButton();
        btnSaveSettings = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        UserSettings = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 750));
        setMinimumSize(new java.awt.Dimension(1000, 750));
        setPreferredSize(new java.awt.Dimension(1000, 750));
        setLayout(new java.awt.GridLayout(1, 0));

        GlobalSettings.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        DataBaseSettings.setLayout(new java.awt.GridLayout(3, 1));

        ServerSettings.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Servidor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 18))); // NOI18N
        ServerSettings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblServerHost.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblServerHost.setText("Server Host:");
        ServerSettings.add(lblServerHost, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 50, -1, -1));

        lblPort.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblPort.setText("Puerto:");
        ServerSettings.add(lblPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 50, -1, -1));

        lblDataBase.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblDataBase.setText("Base de Datos:");
        ServerSettings.add(lblDataBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 107, -1, -1));

        txtServerHost.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        ServerSettings.add(txtServerHost, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 49, 362, 23));

        txtServerPort.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        ServerSettings.add(txtServerPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 47, 410, -1));

        txtDataBaseName.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        ServerSettings.add(txtDataBaseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 104, 825, -1));

        DataBaseSettings.add(ServerSettings);

        AuthenticationSettings.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Autentificación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 18))); // NOI18N
        AuthenticationSettings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUserName.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblUserName.setText("Nombre de usuario:");
        AuthenticationSettings.add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 46, -1, -1));

        lblPassword.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblPassword.setText("Contraseña:");
        AuthenticationSettings.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 110, -1, -1));

        cboxShowPass.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cboxShowPass.setText("Mostrar Contraseña");
        AuthenticationSettings.add(cboxShowPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(772, 163, -1, -1));

        txtUserName.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        AuthenticationSettings.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 43, 759, -1));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AuthenticationSettings.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 106, 759, -1));

        DataBaseSettings.add(AuthenticationSettings);

        ActionsSettings.setMaximumSize(new java.awt.Dimension(1000, 750));
        ActionsSettings.setMinimumSize(new java.awt.Dimension(1000, 750));
        ActionsSettings.setName(""); // NOI18N
        ActionsSettings.setPreferredSize(new java.awt.Dimension(1000, 750));
        ActionsSettings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTestCon.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnTestCon.setText("Probar conexión...");
        ActionsSettings.add(btnTestCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 167, -1, -1));

        btnSaveSettings.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnSaveSettings.setText("Guardar");
        ActionsSettings.add(btnSaveSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 167, -1, -1));

        btnCancel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnCancel.setText("Cancelar");
        ActionsSettings.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(849, 167, -1, -1));

        DataBaseSettings.add(ActionsSettings);

        GlobalSettings.addTab("Conexión a BD", DataBaseSettings);

        javax.swing.GroupLayout UserSettingsLayout = new javax.swing.GroupLayout(UserSettings);
        UserSettings.setLayout(UserSettingsLayout);
        UserSettingsLayout.setHorizontalGroup(
            UserSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        UserSettingsLayout.setVerticalGroup(
            UserSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 714, Short.MAX_VALUE)
        );

        GlobalSettings.addTab("Usuario", UserSettings);

        add(GlobalSettings);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel ActionsSettings;
    public javax.swing.JPanel AuthenticationSettings;
    public javax.swing.JPanel DataBaseSettings;
    public javax.swing.JTabbedPane GlobalSettings;
    public javax.swing.JPanel ServerSettings;
    public javax.swing.JPanel UserSettings;
    public javax.swing.JButton btnCancel;
    public javax.swing.JButton btnSaveSettings;
    public javax.swing.JButton btnTestCon;
    public javax.swing.JCheckBox cboxShowPass;
    private javax.swing.JLabel lblDataBase;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPort;
    private javax.swing.JLabel lblServerHost;
    private javax.swing.JLabel lblUserName;
    public javax.swing.JTextField txtDataBaseName;
    public javax.swing.JPasswordField txtPassword;
    public javax.swing.JTextField txtServerHost;
    public javax.swing.JTextField txtServerPort;
    public javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
